# SCMS Delivery History — Supply Chain Data Analysis

This project analyzes shipment and delivery performance using the SCMS Delivery History Dataset.

**Tools:** Python, Pandas, Power BI

In [2]:
import pandas as pd
dataset_path = r"C:\Users\nurul\OneDrive\Desktop\project 3  python scms delivery history\SCMS_Delivery_History_Dataset.csv"
df_delivery = pd.read_csv(dataset_path)

## Data Profiling

### Dataset Dimensions

In [4]:
df_delivery.shape

(10324, 33)

### Dataset Preview

In [5]:
df_delivery.head()

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,30,19,551.0,29.00,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,...,240,1000,6200.0,6.20,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,...,100,500,40000.0,80.00,0.80,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,38000,121600.0,3.20,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN

### Data Types and Missing Values

In [6]:
df_delivery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10324 entries, 0 to 10323
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            10324 non-null  int64
 1   Project Code                  10324 non-null  object
 2   PQ #                          10324 non-null  object
 3   PO / SO #                     10324 non-null  object
 4   ASN/DN #                      10324 non-null  object
 5   Country                       10324 non-null  object
 6   Managed By                    10324 non-null  object
 7   Fulfill Via                   10324 non-null  object
 8   Vendor INCO Term              10324 non-null  object
 9   Shipment Mode                 9964 non-null   object
 10  PQ First Sent to Client Date  10324 non-null  object
 11  PO Sent to Vendor Date        10324 non-null  object
 12  Scheduled Delivery Date       10324 non-null  object
 13  Delivered to Client Date      10324 non-null  object
 14  Delivery Recorded Date        10324 non-null  object
 15  Product Group                 10324 non-null  object
 16  Sub Classification            10324 non-null  object
 17  Vendor                        10324 non-null  object
 18  Item Description              10324 non-null  object
 19  Molecule/Test Type            10324 non-null  object
 20  Brand                         10324 non-null  object
 21  Dosage                        8588 non-null   object
 22  Dosage Form                   10324 non-null  object
 23  Unit of Measure (Per Pack)    10324 non-null  int64
 24  Line Item Quantity            10324 non-null  int64
 25  Line Item Value               10324 non-null  float64
 26  Pack Price                    10324 non-null  float64
 27  Unit Price                    10324 non-null  float64
 28  Manufacturing Site            10324 non-null  object
 29  First Line Designation        10324 non-null  object
 30  Weight (Kilograms)            10324 non-null  object
 31  Freight Cost (USD)            10324 non-null  object
 32  Line Item Insurance (USD)     10037 non-null  float64
dtypes: float64(4), int64(3), object(26)
memory usage: 2.6+ MB

### Missing Values Overview

Missing values were identified in Shipment Mode, Dosage, and Line Item Insurance (USD).

In [7]:
df_delivery.isnull().sum()

ID                                 0
Project Code                       0
PQ #                               0
PO / SO #                          0
ASN/DN #                           0
Country                            0
Managed By                         0
Fulfill Via                        0
Vendor INCO Term                   0
Shipment Mode                    360
PQ First Sent to Client Date       0
PO Sent to Vendor Date             0
Scheduled Delivery Date            0
Delivered to Client Date           0
Delivery Recorded Date             0
Product Group                      0
Sub Classification                 0
Vendor                             0
Item Description                   0
Molecule/Test Type                 0
Brand                              0
Dosage                          1736
Dosage Form                        0
Unit of Measure (Per Pack)         0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
Unit Price                         0
Manufacturing Site                 0
First Line Designation             0
Weight (Kilograms)                 0
Freight Cost (USD)                 0
Line Item Insurance (USD)        287
dtype: int64

### Duplicate Rows Check

In [8]:
df_delivery.duplicated().sum()

np.int64(0)

### Unique Value Counts

In [9]:
 df_delivery.nunique()

ID                              10324
Project Code                      142
PQ #                             1237
PO / SO #                        6233
ASN/DN #                         7030
Country                            43
Managed By                          4
Fulfill Via                         2
Vendor INCO Term                    8
Shipment Mode                       4
PQ First Sent to Client Date      765
PO Sent to Vendor Date            897
Scheduled Delivery Date          2006
Delivered to Client Date         2093
Delivery Recorded Date           2042
Product Group                       5
Sub Classification                  6
Vendor                             73
Item Description                  184
Molecule/Test Type                 86
Brand                              48
Dosage                             54
Dosage Form                        17
Unit of Measure (Per Pack)         31
Line Item Quantity               5065
Line Item Value                  8741
Pack Price                       1175
Unit Price                        183
Manufacturing Site                 88
First Line Designation              2
Weight (Kilograms)               4688
Freight Cost (USD)               6733
Line Item Insurance (USD)        6722
dtype: int64

### Categorical Variables

#### Shipment Mode Distribution

In [10]:
df_delivery["Shipment Mode"].value_counts(dropna=False)

Shipment Mode
Air            6113
Truck          2830
Air Charter     650
Ocean           371
NaN             360
Name: count, dtype: int64

#### Non-Numeric Freight Cost Categories

In [16]:
df_delivery.loc[
    pd.to_numeric(df_delivery["Freight Cost (USD)"], errors="coerce").isna(),
    "Freight Cost (USD)"
].value_counts()

Freight Cost (USD)
Freight Included in Commodity Cost    1442
Invoiced Separately                    239
See DN-304 (ID#:10589)                  16
See ASN-32231 (ID#:13648)               14
See ASN-31750 (ID#:19272)               14
                                      ...
See DN-921 (ID#:11917)                   1
See DN-2914 (ID#:83089)                  1
See DN-1083 (ID#:12219)                  1
See DN-964 (ID#:10987)                   1
See DN-4282 (ID#:83919)                  1
Name: count, Length: 1301, dtype: int64

### Date Column Selection

In [ ]:
date_columns = [
    "PQ First Sent to Client Date",
    "PO Sent to Vendor Date",
    "Scheduled Delivery Date",
    "Delivered to Client Date",
    "Delivery Recorded Date"
]

for col in date_columns:
    df_delivery[col] = pd.to_datetime(
        df_delivery[col],
        format="%d-%b-%y"
    )

### Raw Date Value Inspection

In [22]:
df_delivery["PQ First Sent to Client Date"].value_counts().head(20)

PQ First Sent to Client Date
Pre-PQ Process       2476
Date Not Captured     205
9/11/14               205
7/11/13               173
4/30/14               123
11/6/09                98
11/21/11               90
3/10/11                89
3/18/10                78
8/31/10                75
2/10/10                72
3/18/13                64
10/13/10               62
12/13/12               56
10/21/13               53
5/7/09                 52
8/9/13                 51
12/8/09                49
10/4/11                48
8/29/11                46
Name: count, dtype: int64

### Date Parsing Validation

### PQ First Sent Date Parsing

In [23]:
pd.to_datetime(
    df_delivery["PQ First Sent to Client Date"],
    errors="coerce"
).notna().sum()

C:\Users\nurul\AppData\Local\Temp\ipykernel_8864\2404643506.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(

np.int64(7643)

### PO Sent to Vendor Date Parsing

In [24]:
pd.to_datetime(df_delivery["PO Sent to Vendor Date"],errors="coerce").notna().sum()

C:\Users\nurul\AppData\Local\Temp\ipykernel_8864\404713946.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df_delivery["PO Sent to Vendor Date"],errors="coerce").notna().sum()

np.int64(4592)

In [25]:
df_delivery.loc[
    pd.to_datetime(df_delivery["PO Sent to Vendor Date"], errors="coerce").isna(),
    "PO Sent to Vendor Date"
].value_counts().head(20)

C:\Users\nurul\AppData\Local\Temp\ipykernel_8864\453920279.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df_delivery["PO Sent to Vendor Date"], errors="coerce").isna(),

PO Sent to Vendor Date
N/A - From RDC       5404
Date Not Captured     328
Name: count, dtype: int64

### Scheduled Delivery Date Parsing

In [26]:
pd.to_datetime(df_delivery["Scheduled Delivery Date"],errors="coerce").notna().sum()

C:\Users\nurul\AppData\Local\Temp\ipykernel_8864\1119045883.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df_delivery["Scheduled Delivery Date"],errors="coerce").notna().sum()

np.int64(10324)

### Delivered to Client Date Parsing

In [27]:
pd.to_datetime(df_delivery["Delivered to Client Date"],errors="coerce").notna().sum()

C:\Users\nurul\AppData\Local\Temp\ipykernel_8864\3688987767.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df_delivery["Delivered to Client Date"],errors="coerce").notna().sum()

np.int64(10324)

### Delivery Recorded Date Parsing

In [28]:
pd.to_datetime(df_delivery["Delivery Recorded Date"],errors="coerce").notna().sum()

C:\Users\nurul\AppData\Local\Temp\ipykernel_8864\2144467454.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df_delivery["Delivery Recorded Date"],errors="coerce").notna().sum()

np.int64(10324)

# Data Cleaning & Transformation

### Convert Date Columns to Datetime

In [29]:
date_columns = ["Scheduled Delivery Date","Delivered to Client Date","Delivery Recorded Date"]

for col in date_columns:
    df_delivery[col]= pd.to_datetime(df_delivery[col],format="%d-%b-%y")

In [30]:
df_delivery[["Scheduled Delivery Date","Delivered to Client Date","Delivery Recorded Date"]].dtypes

Scheduled Delivery Date     datetime64[ns]
Delivered to Client Date    datetime64[ns]
Delivery Recorded Date      datetime64[ns]
dtype: object

### PQ First Sent Date Transformation

In [ ]:
# Convert PQ First Sent to Client Date into datetime

In [32]:
df_delivery["PQ First Sent Date"] = pd.to_datetime(
    df_delivery["PQ First Sent to Client Date"],
    errors="coerce"
)

C:\Users\nurul\AppData\Local\Temp\ipykernel_8864\3290277898.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_delivery["PQ First Sent Date"] = pd.to_datetime(

In [2]:
# Check missing values after date conversion

In [34]:
df_delivery["PQ First Sent Date"].isna().sum()

np.int64(2681)

In [35]:
# Create PQ Date Status to classify date values

In [36]:
df_delivery["PQ Date Status"] = df_delivery["PQ First Sent to Client Date"]

df_delivery.loc[
    df_delivery["PQ First Sent Date"].notna(),
    "PQ Date Status"
] = "Valid Date"

In [37]:
df_delivery["PQ Date Status"].value_counts()

PQ Date Status
Valid Date           7643
Pre-PQ Process       2476
Date Not Captured     205
Name: count, dtype: int64

### PO Sent to Vendor Date Transformation

In [38]:
# Create cleaned PO Sent to Vendor date column

In [40]:
df_delivery["PO Sent to Vendor Clean Date"] = pd.to_datetime(
    df_delivery["PO Sent to Vendor Date"],
    format="mixed",
    errors="coerce"
)

In [41]:
df_delivery["PO Sent to Vendor Clean Date"].notna().sum()

np.int64(4592)

In [42]:
# Create PO Date Status column

In [43]:
df_delivery["PO Date Status"] = df_delivery["PO Sent to Vendor Date"]

df_delivery.loc[
    df_delivery["PO Sent to Vendor Clean Date"].notna(),
    "PO Date Status"
] = "Valid Date"

In [44]:
df_delivery["PO Date Status"].notna().sum()

np.int64(10324)

In [45]:
df_delivery["PO Date Status"].value_counts()

PO Date Status
N/A - From RDC       5404
Valid Date           4592
Date Not Captured     328
Name: count, dtype: int64

 ### Date Data Type Validation

In [46]:
df_delivery[["PQ First Sent Date",
"PO Sent to Vendor Clean Date",
"Scheduled Delivery Date",
"Delivered to Client Date",
"Delivery Recorded Date"]].dtypes

PQ First Sent Date              datetime64[ns]
PO Sent to Vendor Clean Date    datetime64[ns]
Scheduled Delivery Date         datetime64[ns]
Delivered to Client Date        datetime64[ns]
Delivery Recorded Date          datetime64[ns]
dtype: object

### Freight Cost Transformation

In [ ]:
# Convert Freight Cost to numeric values

In [47]:
df_delivery["Freight Cost Numeric"] = pd.to_numeric(df_delivery["Freight Cost (USD)"],errors="coerce")

In [50]:
df_delivery.loc[
    df_delivery["Freight Cost Numeric"].isna(),
    "Freight Cost (USD)"
].value_counts().head(10)

Freight Cost (USD)
Freight Included in Commodity Cost    1442
Invoiced Separately                    239
See DN-304 (ID#:10589)                  16
See ASN-32231 (ID#:13648)               14
See ASN-31750 (ID#:19272)               14
See ASN-28279 (ID#:13547)               13
See DN-3015 (ID#:82554)                 12
See DN-2035 (ID#:82356)                 10
See DN-3561 (ID#:82654)                 10
See ASN-26738 (ID#:15115)               10
Name: count, dtype: int64

In [51]:
df_delivery.loc[
    df_delivery["Freight Cost Numeric"].isna(),
    "Freight Cost (USD)"
].str.startswith(("See DN", "See ASN")).sum()

np.int64(2445)

In [ ]:
# Create Freight Cost Status classification

In [52]:
df_delivery["Freight Cost Status"]=df_delivery["Freight Cost (USD)"]

df_delivery.loc[df_delivery["Freight Cost Numeric"].notna(),"Freight Cost Status"]= "Numeric Cost"

In [53]:
df_delivery["Freight Cost Status"].value_counts().head(10)

Freight Cost Status
Numeric Cost                          6198
Freight Included in Commodity Cost    1442
Invoiced Separately                    239
See DN-304 (ID#:10589)                  16
See ASN-31750 (ID#:19272)               14
See ASN-32231 (ID#:13648)               14
See ASN-28279 (ID#:13547)               13
See DN-3015 (ID#:82554)                 12
See DN-2035 (ID#:82356)                 10
See ASN-26738 (ID#:15115)               10
Name: count, dtype: int64

### Freight Cost Reference Classification

In [54]:
df_delivery.loc[
    df_delivery["Freight Cost (USD)"].str.startswith(("See DN", "See ASN")),
    "Freight Cost Status"
] = "Reference to DN/ASN"

In [55]:
df_delivery["Freight Cost Status"].value_counts()

Freight Cost Status
Numeric Cost                          6198
Reference to DN/ASN                   2445
Freight Included in Commodity Cost    1442
Invoiced Separately                    239
Name: count, dtype: int64

## Missing Value Handling

### Shipment Mode Missing Values

In [56]:
df_delivery.groupby("Country")["Shipment Mode"].apply(
    lambda x: x.isna().sum()
).sort_values(ascending=False).head(12)

Country
Côte d'Ivoire    113
Zambia            99
South Africa      42
Nigeria           36
Tanzania          20
Ethiopia          18
Zimbabwe          12
Uganda             8
Guyana             5
Botswana           3
Haiti              2
Namibia            2
Name: Shipment Mode, dtype: int64

In [57]:
df_delivery["Shipment Mode"].value_counts()

Shipment Mode
Air            6113
Truck          2830
Air Charter     650
Ocean           371
Name: count, dtype: int64

### Shipment Mode Missing Value Handling

In [61]:
df_delivery["Shipment Mode"] = df_delivery["Shipment Mode"].fillna("Unknown")

### Dosage Missing Value Handling

In [68]:
df_delivery.groupby("Product Group")["Dosage"].apply(lambda x: x.isna().sum()).sort_values(ascending=False)

Product Group
HRDT    1728
MRDT       8
ACT        0
ANTM       0
ARV        0
Name: Dosage, dtype: int64

In [ ]:
# Replace missing dosage values with "Not Provided"

In [71]:
df_delivery["Dosage"] = df_delivery["Dosage"].fillna("Not Provided")

In [72]:
df_delivery["Dosage"].value_counts().head(10)

Dosage
Not Provided     1736
300mg             990
200mg             932
600mg             772
150/300mg         600
150/300/200mg     580
10mg/ml           552
150mg             431
200/50mg          395
300/300mg         301
Name: count, dtype: int64

### Delivery Delay and Status Transformation

In [79]:
df_delivery["Delivery Delay Days"] = (
    df_delivery["Delivered to Client Date"]
    - df_delivery["Scheduled Delivery Date"]
).dt.days

In [ ]:
# Classify shipments based on delivery delay days

In [82]:
df_delivery["Delivery Status"] = df_delivery["Delivery Delay Days"].apply(
    lambda x: "Early" if x < 0
    else "On Time" if x == 0
    else "Delayed"
)

In [83]:
df_delivery["Delivery Status"].value_counts()

Delivery Status
On Time    6324
Early      2814
Delayed    1186
Name: count, dtype: int64

In [84]:
df_delivery.shape

(10324, 41)

In [ ]:
# Validate remaining missing values after cleaning

In [85]:
df_delivery.isna().sum().sort_values(ascending=False).head(10)

PO Sent to Vendor Clean Date    5732
Freight Cost Numeric            4126
PQ First Sent Date              2681
Line Item Insurance (USD)        287
ID                                 0
First Line Designation             0
Unit of Measure (Per Pack)         0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
dtype: int64

In [86]:
df_delivery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10324 entries, 0 to 10323
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            10324 non-null  int64
 1   Project Code                  10324 non-null  object
 2   PQ #                          10324 non-null  object
 3   PO / SO #                     10324 non-null  object
 4   ASN/DN #                      10324 non-null  object
 5   Country                       10324 non-null  object
 6   Managed By                    10324 non-null  object
 7   Fulfill Via                   10324 non-null  object
 8   Vendor INCO Term              10324 non-null  object
 9   Shipment Mode                 10324 non-null  object
 10  PQ First Sent to Client Date  10324 non-null  object
 11  PO Sent to Vendor Date        10324 non-null  object
 12  Scheduled Delivery Date       10324 non-null  datetime64[ns]
 13  Delivered to Client Date      10324 non-null  datetime64[ns]
 14  Delivery Recorded Date        10324 non-null  datetime64[ns]
 15  Product Group                 10324 non-null  object
 16  Sub Classification            10324 non-null  object
 17  Vendor                        10324 non-null  object
 18  Item Description              10324 non-null  object
 19  Molecule/Test Type            10324 non-null  object
 20  Brand                         10324 non-null  object
 21  Dosage                        10324 non-null  object
 22  Dosage Form                   10324 non-null  object
 23  Unit of Measure (Per Pack)    10324 non-null  int64
 24  Line Item Quantity            10324 non-null  int64
 25  Line Item Value               10324 non-null  float64
 26  Pack Price                    10324 non-null  float64
 27  Unit Price                    10324 non-null  float64
 28  Manufacturing Site            10324 non-null  object
 29  First Line Designation        10324 non-null  object
 30  Weight (Kilograms)            10324 non-null  object
 31  Freight Cost (USD)            10324 non-null  object
 32  Line Item Insurance (USD)     10037 non-null  float64
 33  PQ First Sent Date            7643 non-null   datetime64[ns]
 34  PQ Date Status                10324 non-null  object
 35  PO Sent to Vendor Clean Date  4592 non-null   datetime64[ns]
 36  PO Date Status                10324 non-null  object
 37  Freight Cost Numeric          6198 non-null   float64
 38  Freight Cost Status           10324 non-null  object
 39  Delivery Delay Days           10324 non-null  int64
 40  Delivery Status               10324 non-null  object
dtypes: datetime64[ns](5), float64(5), int64(4), object(27)
memory usage: 3.2+ MB

### Weight Data Cleaning and Validation

In [88]:
pd.to_numeric(
    df_delivery["Weight (Kilograms)"],
    errors="coerce"
).notna().sum()

np.int64(6372)

In [90]:
df_delivery["Weight Numeric"]=pd.to_numeric(df_delivery["Weight (Kilograms)"],errors="coerce")

In [ ]:
# Classify weight values based on numeric availability

In [92]:
df_delivery["Weight Status"]=df_delivery["Weight (Kilograms)"]

df_delivery.loc[df_delivery["Weight Numeric"].notna(),"Weight Status"] = "Numeric Weight"

In [93]:
df_delivery["Weight Status"].value_counts()

Weight Status
Numeric Weight                6372
Weight Captured Separately    1507
See DN-304 (ID#:10589)          16
See ASN-32231 (ID#:13648)       14
See ASN-31750 (ID#:19272)       14
                              ...
See DN-921 (ID#:11917)           1
See DN-2914 (ID#:83089)          1
See DN-1083 (ID#:12219)          1
See DN-964 (ID#:10987)           1
See DN-4282 (ID#:83919)          1
Name: count, Length: 1301, dtype: int64

In [ ]:
# Identify weight values referenced through DN/ASN documents

In [94]:
df_delivery.loc[
    df_delivery["Weight (Kilograms)"].str.startswith(("See DN", "See ASN")),
    "Weight Status"
] = "Reference to DN/ASN"

In [95]:
df_delivery["Weight Status"].value_counts()

Weight Status
Numeric Weight                6372
Reference to DN/ASN           2445
Weight Captured Separately    1507
Name: count, dtype: int64

In [ ]:
# Validate remaining missing values after data cleaning

In [96]:
df_delivery.isna().sum().sort_values(ascending=False).head(10)

PO Sent to Vendor Clean Date    5732
Freight Cost Numeric            4126
Weight Numeric                  3952
PQ First Sent Date              2681
Line Item Insurance (USD)        287
Weight (Kilograms)                 0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
Unit Price                         0
dtype: int64

## Exploratory Data Analysis (EDA)

### Delivery Status Overview

Assess the overall delivery status of shipments.

In [97]:
df_delivery["Delivery Status"].value_counts()

Delivery Status
On Time    6324
Early      2814
Delayed    1186
Name: count, dtype: int64

# Calculate the percentage distribution of delivery statuses

In [98]:
df_delivery["Delivery Status"].value_counts(normalize=True) * 100

Delivery Status
On Time    61.255327
Early      27.256877
Delayed    11.487795
Name: proportion, dtype: float64

### Delayed Shipment Severity

In [100]:
df_delivery.loc[
    df_delivery["Delivery Delay Days"] > 0,
    "Delivery Delay Days"
].describe()

count    1186.000000
mean       21.369309
std        28.498134
min         1.000000
25%         5.000000
50%        12.000000
75%        24.750000
max       192.000000
Name: Delivery Delay Days, dtype: float64

### Delivery Delay Rate by Country

In [102]:
delayed_rate = (
    df_delivery.groupby("Country")["Delivery Status"]
    .apply(lambda x: (x == "Delayed").mean() * 100)
    .sort_values(ascending=False)
)

delayed_rate.head(10)

Country
Burundi       38.775510
Senegal       33.333333
Togo          33.333333
Congo, DRC    24.924925
Benin         23.076923
Mozambique    18.383518
Zambia        15.812592
Zimbabwe      14.312268
Ghana         13.793103
Guatemala     13.333333
Name: Delivery Status, dtype: float64

#### Delivery Delay Rate for Countries with Sufficient Sample Size

Countries with at least 50 shipments are included to provide a more reliable comparison of delivery delay rates.

In [104]:
delayed_rate_50 = (
    df_delivery.groupby("Country")
    .filter(lambda x: len(x) >= 50)
    .groupby("Country")["Delivery Status"]
    .apply(lambda x: (x == "Delayed").mean() * 100)
    .sort_values(ascending=False)
)

delayed_rate_50

Country
Burundi               38.775510
Congo, DRC            24.924925
Mozambique            18.383518
Zambia                15.812592
Zimbabwe              14.312268
Ghana                 13.793103
South Sudan           12.804878
Tanzania              12.716763
Kenya                 12.612613
Uganda                12.580231
Côte d'Ivoire         12.373038
Nigeria               11.892797
Guyana                10.126582
Haiti                  9.465649
Cameroon               9.333333
Rwanda                 8.604651
South Africa           8.179232
Dominican Republic     7.692308
Ethiopia               5.555556
Botswana               2.857143
Namibia                1.052632
Vietnam                0.872093
Name: Delivery Status, dtype: float64

### Country Delivery Performance Summary

In [105]:
country_delivery = (
    df_delivery.groupby("Country")
    .agg(
        Shipments=("ID", "count"),
        Delayed=("Delivery Status", lambda x: (x == "Delayed").sum())
    )
)

country_delivery["Delayed Rate (%)"] = (
    country_delivery["Delayed"] / country_delivery["Shipments"] * 100
)

country_delivery.sort_values(
    "Delayed Rate (%)",
    ascending=False
).head(10)

            Shipments  Delayed  Delayed Rate (%)
Country
Burundi            98       38         38.775510
Senegal             3        1         33.333333
Togo                3        1         33.333333
Congo, DRC        333       83         24.924925
Benin              13        3         23.076923
Mozambique        631      116         18.383518
Zambia            683      108         15.812592
Zimbabwe          538       77         14.312268
Ghana              58        8         13.793103
Guatemala          15        2         13.333333

### Top Countries by Delivery Delay Rate

In [106]:
country_delivery[country_delivery["Shipments"] >= 50].sort_values(
    "Delayed Rate (%)",
    ascending=False
).head(10)

             Shipments  Delayed  Delayed Rate (%)
Country
Burundi             98       38         38.775510
Congo, DRC         333       83         24.924925
Mozambique         631      116         18.383518
Zambia             683      108         15.812592
Zimbabwe           538       77         14.312268
Ghana               58        8         13.793103
South Sudan        164       21         12.804878
Tanzania           519       66         12.716763
Kenya              111       14         12.612613
Uganda             779       98         12.580231

### Delivery Delay Rate by Shipment Mode

Assess delivery delay rates across different shipment modes.

In [107]:
shipment_mode_delivery = (
    df_delivery.groupby("Shipment Mode")["Delivery Status"]
    .value_counts(normalize=True)
    .mul(100)
    .unstack(fill_value=0)
)

shipment_mode_delivery

Delivery Status    Delayed      Early    On Time
Shipment Mode
Air               9.602487  19.352200  71.045313
Air Charter      11.538462  69.538462  18.923077
Ocean            17.520216   4.043127  78.436658
Truck            16.077739  40.176678  43.745583
Unknown           1.111111   7.500000  91.388889

## Vendor Performance

#### Delivery Delay Rate by Vendor

In [111]:
vendor_delivery = (
    df_delivery.groupby("Vendor")["Delivery Status"]
    .apply(lambda x: (x == "Delayed").mean() * 100)
    .sort_values(ascending=False)
)

vendor_delivery.head(10)

Vendor
SCMS from RDC                                                       17.153960
BIO-RAD LABORATORIES (FRANCE)                                       14.285714
Aurobindo Pharma Limited                                            14.071856
CIPLA LIMITED                                                       13.142857
Orgenics, Ltd                                                       12.997347
SUN PHARMACEUTICAL INDUSTRIES LTD (RANBAXY LABORATORIES LIMITED)    11.111111
REINBOLD EXPORT IMPORT                                               8.333333
EMCURE PHARMACEUTICALS LTD                                           4.878049
Abbott GmbH & Co. KG                                                 4.761905
STRIDES ARCOLAB LIMITED                                              4.301075
Name: Delivery Status, dtype: float64

#### Vendor Delivery Delay Rate with Sufficient Sample Size

Vendors with at least 50 shipments are included to provide a more reliable comparison of delivery delay rates.

In [112]:
vendor_delivery_50 = (
    df_delivery.groupby("Vendor")
    .filter(lambda x: len(x) >= 50)
    .groupby("Vendor")["Delivery Status"]
    .apply(lambda x: (x == "Delayed").mean() * 100)
    .sort_values(ascending=False)
)

vendor_delivery_50.head(10)

Vendor
SCMS from RDC                                                        17.153960
Aurobindo Pharma Limited                                             14.071856
CIPLA LIMITED                                                        13.142857
Orgenics, Ltd                                                        12.997347
STRIDES ARCOLAB LIMITED                                               4.301075
Standard Diagnostics, Inc.                                            4.081633
SHANGHAI KEHUA BIOENGINEERING CO.,LTD.  (KHB)                         2.857143
Orasure Technologies Inc.                                             1.785714
S. BUYS WHOLESALER                                                    1.538462
MERCK SHARP & DOHME IDEA GMBH (FORMALLY MERCK SHARP & DOHME B.V.)     1.470588
Name: Delivery Status, dtype: float64

## Product / Shipment Volume Analysis

In [113]:
df_delivery["Product Group"].value_counts()

Product Group
ARV     8550
HRDT    1728
ANTM      22
ACT       16
MRDT       8
Name: count, dtype: int64

### Delivery Delay Rate by Product Group

In [115]:
product_delivery = (
    df_delivery.groupby("Product Group")["Delivery Status"]
    .apply(lambda x: (x == "Delayed").mean() * 100)
    .sort_values(ascending=False)
)

product_delivery

Product Group
ARV     12.549708
HRDT     6.539352
ACT      0.000000
ANTM     0.000000
MRDT     0.000000
Name: Delivery Status, dtype: float64

## Cost / Financial Analysis

### Total Shipment Value by Product Group

In [117]:
product_value = (
    df_delivery.groupby("Product Group")["Line Item Value"]
    .sum()
    .sort_values(ascending=False)
)

product_value

Product Group
ARV     1.413220e+09
HRDT    2.133448e+08
ACT     6.643809e+05
ANTM    2.741766e+05
MRDT    8.106510e+04
Name: Line Item Value, dtype: float64

### Average Shipment Value by Product Group

In [118]:
df_delivery.groupby("Product Group")["Line Item Value"].mean().sort_values(ascending=False)

Product Group
ARV     165288.897413
HRDT    123463.403825
ACT      41523.808750
ANTM     12462.570909
MRDT     10133.137500
Name: Line Item Value, dtype: float64

### Delivery Delay vs Shipment Value

Assess whether higher-value shipments are associated with delivery delays.

#### Average Shipment Value by Delivery Status

In [125]:
df_delivery.groupby("Delivery Status")["Line Item Value"].mean().sort_values(ascending=False)

Delivery Status
Delayed    218410.009224
Early      211433.022658
On Time    122324.108253
Name: Line Item Value, dtype: float64

#### Median Shipment Value by Delivery Status

In [127]:
df_delivery.groupby("Delivery Status")["Line Item Value"].median().sort_values(ascending=False)

Delivery Status
Delayed    78250.950
Early      39426.975
On Time    22785.190
Name: Line Item Value, dtype: float64

#### Correlation Between Shipment Value and Delivery Delay

In [132]:
df_delivery[["Line Item Value", "Delivery Delay Days"]].corr()

                     Line Item Value  Delivery Delay Days
Line Item Value             1.000000            -0.015638
Delivery Delay Days        -0.015638             1.000000

### Delivery Performance by Country

#### Overall Delayed Rate by Country

#### Delayed Rate by Country — Minimum 50 Shipments

In [135]:
country_delivery_50 = (
    df_delivery.groupby("Country")
    .filter(lambda x: len(x) >= 50)
    .groupby("Country")["Delivery Status"]
    .apply(lambda x: (x == "Delayed").mean() * 100)
    .sort_values(ascending=False)
)

country_delivery_50.head(10)

Country
Burundi        38.775510
Congo, DRC     24.924925
Mozambique     18.383518
Zambia         15.812592
Zimbabwe       14.312268
Ghana          13.793103
South Sudan    12.804878
Tanzania       12.716763
Kenya          12.612613
Uganda         12.580231
Name: Delivery Status, dtype: float64

#### Country Delivery Summary

In [136]:
country_delivery_summary = pd.DataFrame({
    "Shipment Count": df_delivery["Country"].value_counts(),
    "Delayed Rate (%)": country_delivery
})

country_delivery_summary.head(10)

               Shipment Count  Delayed Rate (%)
Country
Afghanistan                 3          0.000000
Angola                      7          0.000000
Belize                      1          0.000000
Benin                      13         23.076923
Botswana                   70          2.857143
Burkina Faso                2          0.000000
Burundi                    98         38.775510
Cameroon                   75          9.333333
Congo, DRC                333         24.924925
Côte d'Ivoire            1083         12.373038

In [139]:
country_delivery_summary.sort_values(
    "Delayed Rate (%)",
    ascending=False
).head(10)

            Shipment Count  Delayed Rate (%)
Country
Burundi                 98         38.775510
Senegal                  3         33.333333
Togo                     3         33.333333
Congo, DRC             333         24.924925
Benin                   13         23.076923
Mozambique             631         18.383518
Zambia                 683         15.812592
Zimbabwe               538         14.312268
Ghana                   58         13.793103
Guatemala               15         13.333333

### Delivery Performance by Shipment Mode

Which shipment modes have different delivery delay rates?

#### Shipment Volume by Shipment Mode

In [140]:
df_delivery["Shipment Mode"].value_counts()

Shipment Mode
Air            6113
Truck          2830
Air Charter     650
Ocean           371
Unknown         360
Name: count, dtype: int64

#### Delayed Rate by Shipment Mode

In [141]:
df_delivery.groupby("Shipment Mode")["Delivery Status"].apply(
    lambda x: (x == "Delayed").mean() * 100
).sort_values(ascending=False)

Shipment Mode
Ocean          17.520216
Truck          16.077739
Air Charter    11.538462
Air             9.602487
Unknown         1.111111
Name: Delivery Status, dtype: float64

#### Shipment Mode Delivery Summary

In [142]:
shipment_mode_summary = pd.DataFrame({
    "Shipment Count": df_delivery["Shipment Mode"].value_counts(),
    "Delayed Rate (%)": df_delivery.groupby("Shipment Mode")["Delivery Status"].apply(
        lambda x: (x == "Delayed").mean() * 100
    )
})

shipment_mode_summary

               Shipment Count  Delayed Rate (%)
Shipment Mode
Air                      6113          9.602487
Air Charter               650         11.538462
Ocean                     371         17.520216
Truck                    2830         16.077739
Unknown                   360          1.111111

### Delivery Delay Severity by Shipment Mode

How severe are delivery delays across shipment modes?

#### Average Delay Days by Shipment Mode

In [145]:
df_delivery[df_delivery["Delivery Status"] == "Delayed"].groupby("Shipment Mode")["Delivery Delay Days"].mean().sort_values(ascending=False)

Shipment Mode
Ocean          39.892308
Unknown        27.750000
Air            23.303237
Truck          17.586813
Air Charter    12.786667
Name: Delivery Delay Days, dtype: float64

#### Shipment Mode Delay Summary

In [150]:
shipment_mode_delay_summary = pd.DataFrame({
    "Shipment Count": df_delivery["Shipment Mode"].value_counts(),
    "Delayed Rate (%)": df_delivery.groupby("Shipment Mode")["Delivery Status"].apply(
        lambda x: (x == "Delayed").mean() * 100
    ),
    "Avg Delay Days": df_delivery[df_delivery["Delivery Status"] == "Delayed"].groupby(
        "Shipment Mode"
    )["Delivery Delay Days"].mean()
})

shipment_mode_delay_summary

               Shipment Count  Delayed Rate (%)  Avg Delay Days
Shipment Mode
Air                      6113          9.602487       23.303237
Air Charter               650         11.538462       12.786667
Ocean                     371         17.520216       39.892308
Truck                    2830         16.077739       17.586813
Unknown                   360          1.111111       27.750000

### Product / Shipment Volume & Value

In [151]:
df_delivery["Product Group"].value_counts()

Product Group
ARV     8550
HRDT    1728
ANTM      22
ACT       16
MRDT       8
Name: count, dtype: int64

#### Shipment Volume and Total Value by Product Group

In [152]:
product_summary = pd.DataFrame({
    "Shipment Count": df_delivery["Product Group"].value_counts(),
    "Total Shipment Value": df_delivery.groupby("Product Group")["Line Item Value"].sum()
})

product_summary

               Shipment Count  Total Shipment Value
Product Group
ACT                        16          6.643809e+05
ANTM                       22          2.741766e+05
ARV                      8550          1.413220e+09
HRDT                     1728          2.133448e+08
MRDT                        8          8.106510e+04

### Delivery Performance Over Time

In [154]:
df_delivery["Delivered to Client Date"].dt.year.value_counts().sort_index()

Delivered to Client Date
2006      65
2007     671
2008    1108
2009    1192
2010    1176
2011    1049
2012    1253
2013    1240
2014    1573
2015     997
Name: count, dtype: int64

#### Delayed Rate by Year

In [155]:
df_delivery.groupby(
    df_delivery["Delivered to Client Date"].dt.year
)["Delivery Status"].apply(
    lambda x: (x == "Delayed").mean() * 100
).sort_index()

Delivered to Client Date
2006     0.000000
2007     1.639344
2008     1.444043
2009     3.691275
2010    14.795918
2011    23.832221
2012     8.539505
2013    15.806452
2014    17.037508
2015    12.036108
Name: Delivery Status, dtype: float64

#### Yearly Delivery Performance Summary

In [157]:
yearly_delivery_summary = pd.DataFrame({
    "Shipment Count": df_delivery["Delivered to Client Date"].dt.year.value_counts(),
    "Delayed Rate (%)": df_delivery.groupby(
        df_delivery["Delivered to Client Date"].dt.year
    )["Delivery Status"].apply(
        lambda x: (x == "Delayed").mean() * 100
    )
}).sort_index()

yearly_delivery_summary

                          Shipment Count  Delayed Rate (%)
Delivered to Client Date
2006                                  65          0.000000
2007                                 671          1.639344
2008                                1108          1.444043
2009                                1192          3.691275
2010                                1176         14.795918
2011                                1049         23.832221
2012                                1253          8.539505
2013                                1240         15.806452
2014                                1573         17.037508
2015                                 997         12.036108

#### Average Delay Days by Year

In [158]:
df_delivery[df_delivery["Delivery Status"] == "Delayed"].groupby(
    df_delivery["Delivered to Client Date"].dt.year
)["Delivery Delay Days"].mean().sort_index()

Delivered to Client Date
2007    25.727273
2008    20.500000
2009    13.181818
2010    15.689655
2011    27.368000
2012    12.504673
2013    17.204082
2014    30.891791
2015    13.266667
Name: Delivery Delay Days, dtype: float64

#### Delayed Rate by Fulfillment Method

In [159]:
df_delivery.groupby("Fulfill Via")["Delivery Status"].apply(
    lambda x: (x == "Delayed").mean() * 100
).sort_values(ascending=False)

Fulfill Via
From RDC       17.153960
Direct Drop     5.264228
Name: Delivery Status, dtype: float64

#### Total Line Item Quantity by Product Group

In [162]:
df_delivery.groupby("Product Group")["Line Item Quantity"].sum().sort_values(ascending=False)

Product Group
ARV     185008389
HRDT      4098414
ACT        134286
ANTM        21023
MRDT         2978
Name: Line Item Quantity, dtype: int64

### Final Missing Value Check

In [164]:
df_delivery.isnull().sum().sort_values(ascending=False)

PO Sent to Vendor Clean Date    5732
Freight Cost Numeric            4126
Weight Numeric                  3952
PQ First Sent Date              2681
Line Item Insurance (USD)        287
Weight (Kilograms)                 0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
Unit Price                         0
Manufacturing Site                 0
First Line Designation             0
ID                                 0
Freight Cost (USD)                 0
Dosage Form                        0
PQ Date Status                     0
PO Date Status                     0
Freight Cost Status                0
Delivery Delay Days                0
Delivery Status                    0
Unit of Measure (Per Pack)         0
Dosage                             0
Project Code                       0
PQ First Sent to Client Date       0
PQ #                               0
PO / SO #                          0
ASN/DN #                           0
Country                            0
Managed By                         0
Fulfill Via                        0
Vendor INCO Term                   0
Shipment Mode                      0
PO Sent to Vendor Date             0
Brand                              0
Scheduled Delivery Date            0
Delivered to Client Date           0
Delivery Recorded Date             0
Product Group                      0
Sub Classification                 0
Vendor                             0
Item Description                   0
Molecule/Test Type                 0
Weight Status                      0
dtype: int64

## 4. Export Cleaned Dataset

The cleaned dataset is exported as a CSV file for use in Power BI.

In [167]:
df_delivery.to_csv(
    "SCMS_Delivery_History_Cleaned.csv",
    index=False
)